
# Build
FROM node:14 as build
WORKDIR /app
COPY ../package*.json ./
COPY ../.env.prod ./
RUN npm install
COPY ../public public/
COPY ../src src/
RUN npm run build

# Copy travel_ssl.conf to /etc/nginx/vhosts
FROM nginx:alpine
WORKDIR /etc/nginx/vhosts
COPY ../nginx_config/travel_ssl.conf ./

# Replace nginx.conf in /etc/nginx
WORKDIR /etc/nginx
RUN rm -f nginx.conf
COPY ../nginx_config/nginx.conf ./

# Copy ssl certificate to /etc/nginx/ssl_certificate/travel
WORKDIR /etc/nginx/ssl_certificate/travel
COPY ../ssl_certificate/travel/6713133_travel.aeeternity.com.pem ./
COPY ../ssl_certificate/travel/6713133_travel.aeeternity.com.key ./

# Rename the build folder to workspace
WORKDIR /workspace/travel
COPY --from=build /app/build/ ./
EXPOSE 80
CMD [ "nginx", "-g", "daemon off;" ]
